# Generated by Django 5.2.6 on 2025-09-26 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('hiring_manager', 'Hiring Manager'), ('supervisor', 'Supervisor'), ('human_resources', 'Human Resources')], default='manager', max_length=50),
        ),
    ]
