# Generated by Django 5.2.6 on 2025-09-26 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_prf_other_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='prf',
            name='is_salary_range',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prf',
            name='immediate_supervisor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reason_for_posting', to=settings.AUTH_USER_MODEL),
        ),
    ]
