# Generated by Django 5.2.6 on 2025-09-26 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_prf_is_salary_range_alter_prf_immediate_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prf',
            name='immediate_supervisor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervised_prfs', to=settings.AUTH_USER_MODEL),
        ),
    ]
