# Generated by Django 5.2.6 on 2025-09-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_position_active_position_published_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationform',
            old_name='job_name1',
            new_name='preferred_interview_schedule',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='company',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='job_name',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='years_experience',
        ),
        migrations.AddField(
            model_name='applicationform',
            name='upload_med_cert',
            field=models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('disabled', 'Disabled')], default='optional', max_length=50),
        ),
    ]
