# Generated by Django 5.2.6 on 2025-09-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_job_name1_applicationform_preferred_interview_schedule_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pipelinestep',
            options={'ordering': ['stage', 'order']},
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='position_applying_for',
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='pipelinestep',
            name='order',
            field=models.PositiveIntegerField(help_text='Order of this step within its stage (1, 2, 3, etc.)'),
        ),
        migrations.AlterField(
            model_name='pipelinestep',
            name='stage',
            field=models.PositiveIntegerField(choices=[(1, 'Stage 1'), (2, 'Stage 2'), (3, 'Stage 3'), (4, 'Stage 4')], help_text='Which stage this step belongs to (1-4)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.'),
        ),
        migrations.AlterUniqueTogether(
            name='pipelinestep',
            unique_together={('position', 'stage', 'order')},
        ),
    ]
