# Generated by Django 5.2.6 on 2025-09-30 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_pipelinestep_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='headcount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
