# Generated by Django 5.2.6 on 2025-10-01 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_applicationform_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='position',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application_form', to='core.position'),
        ),
    ]
