# Generated by Django 5.2.6 on 2025-10-03 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_position_work_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='qualifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='position',
            name='responsibilities',
            field=models.TextField(blank=True),
        ),
    ]
