# Generated by Django 5.2.6 on 2025-10-03 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_position_qualifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='position',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.client'),
        ),
        migrations.AlterField(
            model_name='position',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_positions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prf',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_prfs', to=settings.AUTH_USER_MODEL),
        ),
    ]
