# Generated by Django 5.2.6 on 2025-10-08 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_rename_job_description_prf_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prf',
            name='active',
        ),
    ]
