# Generated by Django 5.2.6 on 2025-10-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_prf_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='prf',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
