# Generated by Django 5.2.6 on 2025-10-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_prf_contract_type_remove_prf_work_arrangement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prf',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('temporary', 'Temporary')], max_length=100),
        ),
        migrations.AlterField(
            model_name='prf',
            name='work_setup',
            field=models.CharField(choices=[('onsite', 'Onsite'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], max_length=100),
        ),
    ]
