# Generated by Django 5.2.6 on 2025-10-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_prf_employment_type_alter_prf_work_setup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='business_unit',
            field=models.CharField(choices=[('oodc', 'OODC'), ('oors', 'OORS')], default='oodc', max_length=100),
        ),
    ]
