# Generated by Django 5.2.6 on 2025-10-09 01:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_user_business_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='headcount',
            new_name='number_of_vacancies',
        ),
        migrations.AlterField(
            model_name='prf',
            name='number_of_vacancies',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
