# Generated by Django 5.2.6 on 2025-10-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_rename_headcount_position_number_of_vacancies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='type',
            field=models.CharField(default='position', max_length=50),
        ),
        migrations.AddField(
            model_name='prf',
            name='type',
            field=models.CharField(default='prf', max_length=50),
        ),
    ]
