# Generated by Django 5.2.6 on 2025-10-09 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_position_type_prf_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='type',
            field=models.CharField(choices=[('position', 'Position')], default='position', max_length=50),
        ),
        migrations.AlterField(
            model_name='prf',
            name='type',
            field=models.CharField(choices=[('prf', 'PRF')], default='prf', max_length=50),
        ),
    ]
