# Generated by Django 5.2.6 on 2025-10-09 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_position_type_alter_prf_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='date_needed',
            new_name='target_start_date',
        ),
    ]
