# Generated by Django 5.2.6 on 2025-10-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_rename_date_needed_position_target_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='prf',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='active', max_length=50),
        ),
    ]
