# Generated by Django 5.2.6 on 2025-09-26 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('attempt', models.IntegerField(default=0)),
                ('business_unit', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=50)),
                ('role', models.CharField(default='manager', max_length=50)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='core_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='core_user_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PRF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('target_start_date', models.DateField()),
                ('number_of_vacancies', models.IntegerField()),
                ('reason_for_posting', models.CharField(max_length=100)),
                ('other_reason_for_posting', models.CharField(blank=True, max_length=100)),
                ('business_unit', models.CharField(choices=[('oodc', 'OODC'), ('oors', 'OORS')], max_length=100)),
                ('department_name', models.CharField(max_length=100)),
                ('interview_levels', models.IntegerField()),
                ('contract_type', models.CharField(max_length=100)),
                ('work_arrangement', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('working_site', models.CharField(max_length=100)),
                ('work_schedule_from', models.TimeField()),
                ('work_schedule_to', models.TimeField()),
                ('job_description', models.TextField()),
                ('responsibilities', models.TextField()),
                ('qualifications', models.TextField()),
                ('non_negotiables', models.TextField(blank=True)),
                ('salary_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('assessment_required', models.BooleanField(default=False)),
                ('assessment_types', models.JSONField(blank=True, default=dict, null=True)),
                ('other_assessment', models.TextField(blank=True)),
                ('hardware_required', models.JSONField(blank=True, default=dict, null=True)),
                ('software_required', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hiring_managers', models.ManyToManyField(blank=True, related_name='prfs_as_hiring_manager', to='core.user')),
                ('immediate_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reason_for_posting', to='core.user')),
            ],
        ),
    ]
