# Generated by Django 5.2.6 on 2025-09-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_prf_immediate_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='prf',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
