# Generated by Django 5.2.6 on 2025-09-30 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_prf_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='prf',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_prfs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('education_level', models.CharField(choices=[('high_school', 'High School'), ('associate', 'Associate Degree'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('doctorate', 'Doctorate Degree')], max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level'), ('junior', 'Junior'), ('mid', 'Mid Level'), ('senior', 'Senior'), ('lead', 'Lead'), ('executive', 'Executive')], max_length=50)),
                ('work_setup', models.CharField(max_length=50)),
                ('date_needed', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='active', max_length=50)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('temporary', 'Temporary')], max_length=50)),
                ('reason_for_hiring', models.CharField(max_length=255)),
                ('other_reason_for_hiring', models.CharField(blank=True, max_length=255, null=True)),
                ('min_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='PipelineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_type', models.CharField(choices=[('resume_screening', 'Resume Screening'), ('phone_interview', 'Phone Interview'), ('initial_interview', 'Initial Interview'), ('assessments', 'Assessments'), ('final_interview', 'Final Interview'), ('offer', 'Offer'), ('onboarding', 'Onboarding')], max_length=50)),
                ('process_title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField()),
                ('stage', models.PositiveIntegerField()),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline', to='core.position')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('disabled', 'Disabled')], default='optional', max_length=50)),
                ('birth_date', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('disabled', 'Disabled')], default='optional', max_length=50)),
                ('gender', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('disabled', 'Disabled')], default='optional', max_length=50)),
                ('primary_contact_number', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('disabled', 'Disabled')], default='optional', max_length=50)),
                ('secondary_contact_number', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('disabled', 'Disabled')], default='optional', max_length=50)),
                ('email', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('disabled', 'Disabled')], default='optional', max_length=50)),
                ('linkedin_profile', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('disabled', 'Disabled')], default='optional', max_length=50)),
                ('address', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('disabled', 'Disabled')], default='optional', max_length=50)),
                ('job_name', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('disabled', 'Disabled')], default='optional', max_length=50)),
                ('company', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('disabled', 'Disabled')], default='optional', max_length=50)),
                ('years_experience', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('disabled', 'Disabled')], default='optional', max_length=50)),
                ('position_applying_for', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('disabled', 'Disabled')], default='optional', max_length=50)),
                ('expected_salary', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('disabled', 'Disabled')], default='optional', max_length=50)),
                ('willing_to_work_onsite', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('disabled', 'Disabled')], default='optional', max_length=50)),
                ('photo_2x2', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('disabled', 'Disabled')], default='optional', max_length=50)),
                ('education_attained', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('disabled', 'Disabled')], default='optional', max_length=50)),
                ('year_graduated', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('disabled', 'Disabled')], default='optional', max_length=50)),
                ('university', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('disabled', 'Disabled')], default='optional', max_length=50)),
                ('course', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('disabled', 'Disabled')], default='optional', max_length=50)),
                ('work_experience', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('disabled', 'Disabled')], default='optional', max_length=50)),
                ('job_name1', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('disabled', 'Disabled')], default='optional', max_length=50)),
                ('how_did_your_hear_about_us', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('disabled', 'Disabled')], default='optional', max_length=50)),
                ('agreement', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('disabled', 'Disabled')], default='optional', max_length=50)),
                ('signature', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('disabled', 'Disabled')], default='optional', max_length=50)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_form', to='core.position')),
            ],
        ),
    ]
