# Generated by Django 5.2.6 on 2025-09-30 07:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_position_created_at_position_posted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='position',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pipelinestep',
            name='stage',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxLengthValidator(4)]),
        ),
    ]
