# Generated by Django 5.2.6 on 2025-10-01 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_position_headcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_form', to='core.position', unique=True),
        ),
    ]
