# Generated by Django 5.2.6 on 2025-10-02 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_applicationform_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationform',
            old_name='how_did_your_hear_about_us',
            new_name='how_did_you_hear_about_us',
        ),
    ]
