# Generated by Django 5.2.6 on 2025-10-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_how_did_your_hear_about_us_applicationform_how_did_you_hear_about_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='work_setup',
            field=models.CharField(choices=[('onsite', 'Onsite'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], max_length=50),
        ),
    ]
