# Generated by Django 5.2.6 on 2025-10-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_position_qualifications_position_responsibilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='qualifications',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='position',
            name='responsibilities',
            field=models.TextField(),
        ),
    ]
