# Generated by Django 5.2.6 on 2025-10-08 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_prf_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prf',
            old_name='job_description',
            new_name='description',
        ),
    ]
