# Generated by Django 5.2.6 on 2025-10-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_prf_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prf',
            name='contract_type',
        ),
        migrations.RemoveField(
            model_name='prf',
            name='work_arrangement',
        ),
        migrations.AddField(
            model_name='prf',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('temporary', 'Temporary')], default='full_time', max_length=100),
        ),
        migrations.AddField(
            model_name='prf',
            name='work_setup',
            field=models.CharField(choices=[('onsite', 'Onsite'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='onsite', max_length=100),
        ),
    ]
