# Generated by Django 5.2.6 on 2025-10-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_prf_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prf',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='active', max_length=50),
        ),
    ]
