# Generated by Django 5.2.6 on 2025-10-09 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_position_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prf',
            old_name='department_name',
            new_name='department',
        ),
    ]
